### ISSUE TITLE
Cannot import distance function

### ISSUE THREAD

**Issue by L1lith** [erikyo/color-2-name#9]
`SyntaxError: The requested module 'color-2-name' does not provide an export named 'distance'`
I'm getting this error. It's weird because I don't remember changing anything and it was working a few days ago.

The relevant code:
```
import { closest, distance } from "color-2-name";
```

Running in NodeJS v18.17.0 directly with no bundler on Windows 10 LTSC

**Comment by erikyo** [comment]
Thank you, @L1lith, for the report.

I believe there was an issue with the module export in the previous version of package.json.

👇 Here is a playground for you to try out. Please let me know if you still encounter any problems. Thanks again!
https://stackblitz.com/edit/vitejs-vite-t88xtq?file=index.html
